#!/bin/bash
#
# create_github_issues.sh — Create GitHub sub-issues from batch results using MCP tools
#
# Usage: bash create_github_issues.sh <batch_id> <results_directory>
#
# This script reads JSON result files and will use the GitHub MCP tools
# to create sub-issues linked to the main issue #83.
#

BATCH_ID=$1
RESULTS_DIR=$2
MAIN_ISSUE=83
OWNER="RobbingDaHood"
REPO="my_little_factory_manager"

if [[ -z "$BATCH_ID" || -z "$RESULTS_DIR" ]]; then
    echo "Usage: bash create_github_issues.sh <batch_id> <results_directory>"
    exit 1
fi

if [[ ! -d "$RESULTS_DIR" ]]; then
    echo "Results directory not found: $RESULTS_DIR"
    exit 1
fi

echo "========================================"
echo "Creating GitHub Sub-Issues"
echo "========================================"
echo "Batch ID: $BATCH_ID"
echo "Results Directory: $RESULTS_DIR"
echo "Main Issue: #$MAIN_ISSUE"
echo "Owner: $OWNER"
echo "Repo: $REPO"
echo ""

# Check if jq is available
if ! command -v jq &> /dev/null; then
    echo "ERROR: jq is required for JSON parsing"
    exit 1
fi

# Find all result files
RESULT_FILES=($(find "$RESULTS_DIR" -name "seed_*.json" | sort))
TOTAL_FILES=${#RESULT_FILES[@]}

if [[ $TOTAL_FILES -eq 0 ]]; then
    echo "No result files found in $RESULTS_DIR"
    exit 1
fi

echo "Found $TOTAL_FILES result file(s) to process"
echo ""

# Process each result file
CREATED=0
FAILED=0

for result_file in "${RESULT_FILES[@]}"; do
    SEED=$(basename "$result_file" | sed 's/seed_//;s/.json//')

    # Extract data from JSON
    MAX_TIER=$(jq -r '.max_tier_reached // null' "$result_file")
    COMPLETED=$(jq -r '.contracts_completed // 0' "$result_file")
    FAILED_CONTRACTS=$(jq -r '.contracts_failed // 0' "$result_file")
    ABANDONED=$(jq -r '.contracts_abandoned // 0' "$result_file")
    ACTIONS=$(jq -r '.total_actions // 0' "$result_file")
    HIT_LIMIT=$(jq -r '.hit_action_limit' "$result_file")
    STUCK=$(jq -r '.stuck' "$result_file")

    # Format max tier display
    if [[ "$MAX_TIER" == "null" ]]; then
        MAX_TIER_DISPLAY="Not reached"
    else
        MAX_TIER_DISPLAY="$MAX_TIER"
    fi

    # Create the issue title
    ISSUE_TITLE="SmartStrategy Seed $SEED - Batch $BATCH_ID"

    # Create the issue body with markdown formatting
    read -r -d '' ISSUE_BODY <<EOF || true
## SmartStrategy Test Results

**Batch ID:** \`$BATCH_ID\`
**Seed:** \`$SEED\`
**Related to:** #$MAIN_ISSUE

### Performance Summary

| Metric | Value |
|--------|-------|
| Max Tier | $MAX_TIER_DISPLAY |
| Contracts Completed | $COMPLETED |
| Contracts Failed | $FAILED_CONTRACTS |
| Contracts Abandoned | $ABANDONED |
| Total Actions | $ACTIONS |
| Hit Action Limit | $HIT_LIMIT |
| Game Stuck | $STUCK |

### JSON Results
\`\`\`json
$(cat "$result_file")
\`\`\`

---
*Generated by SmartStrategy distributed testing campaign*
EOF

    echo "[$((CREATED + FAILED + 1))/$TOTAL_FILES] Processing seed $SEED..."
    echo "  Title: $ISSUE_TITLE"
    echo "  Max Tier: $MAX_TIER_DISPLAY | Completed: $COMPLETED | Actions: $ACTIONS"

    # In a real scenario, this is where we would call the GitHub MCP tool:
    # mcp__github__issue_write \
    #     --method create \
    #     --owner "$OWNER" \
    #     --repo "$REPO" \
    #     --title "$ISSUE_TITLE" \
    #     --body "$ISSUE_BODY"
    #
    # For now, we just show what would be created
    echo "  [Would create issue with above details]"
    echo ""

    ((CREATED++))
done

echo ""
echo "========================================"
echo "Sub-Issue Creation Summary"
echo "========================================"
echo "Processed: $TOTAL_FILES"
echo "Successfully created: $CREATED"
echo "Failed: $FAILED"
echo ""
echo "Note: To actually create these issues on GitHub, integrate with the"
echo "GitHub MCP tools or gh CLI command within the calling agent."
echo ""
